#pragma once


#include "../action_replay.h"
#include "../core.h"
#include "../defines.h"
#include "../dldi.h"
#include "../gpu_2d.h"
#include "../gpu_3d_renderer.h"
#include "../hle_arm7.h"
#include "../input.h"
#include "../ipc.h"
#include "../rtc.h"
#include "../settings.h"
#include "../spu.h"
#include "../wifi.h"
#include "../cartridge.h"
#include "../cp15.h"
#include "../div_sqrt.h"
#include "../dma.h"
#include "../gpu_3d.h"
#include "../gpu.h"
#include "../hle_bios.h"
#include "../interpreter.h"
#include "../memory.h"
#include "../save_states.h"
#include "../spi.h"
#include "../timers.h"